export const CREATE_HISTORICAL_DATA = "CREATE_HISTORICAL_DATA";
export const CHANGE_FORM_HISTORICAL_DATA_TYPE =
  "CHANGE_FORM_HISTORICAL_DATA_TYPE";
export const CHANGE_FORM_TIME = "CHANGE_FORM_TIME";
export const CHANGE_FORM_PLACE = "CHANGE_FORM_PLACE";
export const CHANGE_FORM_VALUE = "CHANGE_FORM_VALUE";
export const CHANGE_FORM_UNIT = "CHANGE_FORM_UNIT";
export const CHANGE_FORM_PRECIPITATION_TYPE = "CHANGE_FORM_PRECIPITATION_TYPE";
export const CHANGE_FORM_DIRECTION = "CHANGE_FORM_DIRECTION";
