export const GET_DATA_START = "GET_DATA_START";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const GET_DATA_FOR_PLACE = "GET_DATA_FOR_PLACE";
export const GET_DATA_FOR_PLACE_SUCCESS = "GET_DATA_FOR_PLACE_SUCCESS";
export const CHANGE_PLACE = "CHANGE_PLACE";
